## 1. Built-in `random` Module

In [1]:
import random

print("--- Standard Python Random ---")
# Random float between 0.0 and 1.0
print("Random Float [0, 1):", random.random())

# Random integer within a range [a, b]
print("Random Integer [1, 10]:", random.randint(1, 10))

# Random float within a range
print("Random Uniform [5.5, 10.5]:", random.uniform(5.5, 10.5))

# Random choice from a sequence
colors = ["Red", "Green", "Blue", "Yellow"]
print("Random Choice:", random.choice(colors))

# Random sample (multiple unique items)
print("Random Sample (2 items):", random.sample(colors, 2))

# Shuffle a list in place
deck = [1, 2, 3, 4, 5]
random.shuffle(deck)
print("Shuffled List:", deck)

--- Standard Python Random ---
Random Float [0, 1): 0.8749168279789673
Random Integer [1, 10]: 6
Random Uniform [5.5, 10.5]: 7.934412870736552
Random Choice: Green
Random Sample (2 items): ['Yellow', 'Green']
Shuffled List: [1, 3, 4, 2, 5]


## 2. NumPy: Sequences & Distributions

In [2]:
import numpy as np

# Set a seed for reproducibility
np.random.seed(42)

print("--- NumPy Random Arrays ---")
# Generate an array of random integers
ints = np.random.randint(low=10, high=50, size=5)
print("Array of Integers:", ints)

# Uniform distribution [0, 1) of specific shape
uniform_arr = np.random.rand(2, 3) # 2x3 matrix
print("\n2x3 Uniform Matrix:\n", uniform_arr.round(2))

# Normal (Gaussian) distribution: mean=0, std=1
normal_arr = np.random.randn(5)
print("\nStandard Normal Array:", normal_arr.round(2))

# Custom Normal distribution: mean=100, std=15
iq_scores = np.random.normal(loc=100, scale=15, size=5)
print("Custom Normal (IQ Scores):", iq_scores.round(1))

# Binomial distribution (e.g., 10 coin flips, p=0.5, repeated 5 times)
coin_flips = np.random.binomial(n=10, p=0.5, size=5)
print("Binomial (Heads out of 10 flips):", coin_flips)

--- NumPy Random Arrays ---
Array of Integers: [48 38 24 17 30]

2x3 Uniform Matrix:
 [[0.16 0.16 0.06]
 [0.87 0.6  0.71]]

Standard Normal Array: [-0.47  0.54 -0.46 -0.47  0.24]
Custom Normal (IQ Scores): [ 71.3  74.1  91.6  84.8 104.7]
Binomial (Heads out of 10 flips): [4 4 5 6 4]


## 3. Categorical & String Data Generation

In [3]:
import string

n_samples = 10

# Generating categories with specific probabilities
categories = ["Electronics", "Clothing", "Home", "Toys"]
probs = [0.4, 0.3, 0.2, 0.1] # Must sum to 1.0
synth_cats = np.random.choice(categories, size=n_samples, p=probs)
print("Weighted Categories:", synth_cats)

# Generating random strings (e.g., Order IDs or Promo Codes)
def generate_codes(n, length=6):
    chars = string.ascii_uppercase + string.digits
    return [''.join(np.random.choice(list(chars), length)) for _ in range(n)]

promo_codes = generate_codes(5)
print("\nRandom Promo Codes:", promo_codes)

Weighted Categories: ['Clothing' 'Clothing' 'Electronics' 'Clothing' 'Electronics'
 'Electronics' 'Toys' 'Toys' 'Home' 'Electronics']

Random Promo Codes: ['BT1GH8', 'NQ9DBF', 'D2RZ7J', '9N4OHN', 'WUPRXZ']


## 4. Time Series Data with Pandas

In [4]:
import pandas as pd

print("--- Time Series Generation ---")
# Generate a sequence of dates (daily)
date_range = pd.date_range(start="2024-01-01", periods=7, freq='D')
print("Daily Date Range:\n", date_range)

# Generate random walks (useful for simulating stock prices)
steps = np.random.normal(loc=0, scale=1, size=7)
random_walk = np.cumsum(steps) # Cumulative sum of steps
start_price = 100
simulated_prices = start_price + random_walk

# Combine into a Series
ts_data = pd.Series(simulated_prices.round(2), index=date_range)
print("\nSimulated Stock Prices:\n", ts_data)

--- Time Series Generation ---
Daily Date Range:
 DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07'],
              dtype='datetime64[ns]', freq='D')

Simulated Stock Prices:
 2024-01-01    100.10
2024-01-02    100.52
2024-01-03     99.56
2024-01-04     98.51
2024-01-05     96.64
2024-01-06     95.27
2024-01-07     95.91
Freq: D, dtype: float64


## 5. Building Synthetic DataFrames

In [5]:
# Let's combine everything to create a realistic mock dataset
n_rows = 15

df_mock = pd.DataFrame({
    "user_id": range(1001, 1001 + n_rows),
    "join_date": pd.date_range(start="2023-01-01", periods=n_rows, freq='W'),
    "age": np.random.randint(18, 65, size=n_rows),
    "status": np.random.choice(["Active", "Inactive", "Pending"], size=n_rows, p=[0.7, 0.2, 0.1]),
    "monthly_spend": np.random.normal(loc=50, scale=15, size=n_rows).round(2),
    "satisfaction_score": np.random.randint(1, 6, size=n_rows)
})

# Introduce some missing values randomly for realism
missing_idx = np.random.choice(df_mock.index, size=3, replace=False)
df_mock.loc[missing_idx, "satisfaction_score"] = np.nan

print("Synthetic User Database:")
df_mock

Synthetic User Database:


,user_id,join_date,age,status,monthly_spend,satisfaction_score
0,1001,2023-01-01,52,Active,36.40,5.0
1,1002,2023-01-08,50,Active,49.10,NaN
2,1003,2023-01-15,22,Active,64.42,4.0
3,1004,2023-01-22,59,Active,76.91,4.0
4,1005,2023-01-29,56,Active,58.71,4.0
5,1006,2023-02-05,58,Pending,54.46,4.0
6,1007,2023-02-12,45,Inactive,34.58,3.0
7,1008,2023-02-19,24,Inactive,28.72,2.0
8,1009,2023-02-26,26,Active,52.86,4.0
9,1010,2023-03-05,25,Active,52.04,1.0


## 6. Scikit-Learn: ML Dataset Generators

In [7]:
from sklearn.datasets import make_classification, make_regression, make_blobs

print("--- Generating Data for Machine Learning ---")

# 1. Classification Data
# Generates features (X) and target labels (y)
X_clf, y_clf = make_classification(n_samples=5, n_features=4, n_classes=2, random_state=42)
print("\nClassification Features (X):\n", X_clf.round(2))
print("Classification Targets (y):", y_clf)

# 2. Regression Data
# Generates features and continuous target values
X_reg, y_reg = make_regression(n_samples=5, n_features=2, noise=0.1, random_state=42)
print("\nRegression Features (X):\n", X_reg.round(2))
print("Regression Targets (y):", y_reg.round(2))

# 3. Clustering Data (Blobs)
# Generates isotropic Gaussian blobs for clustering
X_blobs, y_blobs = make_blobs(n_samples=5, n_features=2, centers=3, random_state=42)
print("\nClustering Features (X):\n", X_blobs.round(2))
print("Cluster Assignments (y):", y_blobs)

--- Generating Data for Machine Learning ---

Classification Features (X):
 [[ 1.38  0.49 -0.47 -0.13]
 [-2.01 -1.33  0.13  0.73]
 [-1.26 -1.32 -0.35  0.88]
 [-1.02  1.27  1.81 -1.32]
 [ 0.28 -0.98 -1.07  0.92]]
Classification Targets (y): [1 0 0 1 0]

Regression Features (X):
 [[ 0.5  -0.14]
 [ 0.65  1.52]
 [-0.23 -0.23]
 [-0.47  0.54]
 [ 1.58  0.77]]
Regression Targets (y): [ 6.52 39.52 -8.72  1.31 42.73]

Clustering Features (X):
 [[-0.93  9.78]
 [ 4.88  0.06]
 [-2.98  9.56]
 [-8.6  -7.44]
 [ 4.18  1.51]]
Cluster Assignments (y): [0 1 0 2 1]
